config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  post '/homes/guest_sign_in', to: 'homes#new_guest'
  root 'homes#top'
  get 'homes/about'
  get '/search', to: 'searchs#search'

  resources :items do
    resources :item_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end

  resources :users, only: [:show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end
  resources :coordinetes, only: [:index, :create, :edit, :update, :destroy]
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :user
  belongs_to :follow, class_name: 'User'

  validates :user_id, presence: true
  validates :follow_id, presence: true
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  before_action :ensure_user, only: [:create, :destroy, :followings, :followers]

  def create
    following = current_user.follow(@user)
    following.save
    flash[:success] = "フォローしました"
  end

  def destroy
    following = current_user.unfollow(@user)
    following.destroy
    flash[:success] = "フォローを解除しました"
  end

  def followings
    @users = @user.followings
  end

  def followers
    @users = @user.followers
  end

  private

  def ensure_user
    @user = User.find(params[:user_id])
  end
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/views/relationships/_follow_button.html.erb
<div class='row'>
  <% unless current_user == user %>
    <% if current_user.following?(user) %>
      <%= link_to 'Unfollow', user_relationships_path(user.id), class: 'btn btn-info', method: :delete, remote: true %>
    <% else %>
      <%= link_to 'Follow', user_relationships_path(user.id), class: 'btn btn-success', method: :post, remote: true %>
    <% end %>
  <% else %>
    <%= link_to '',edit_user_path(user),class: "btn btn-outline-secondary btn-lg fas fa-user-cog" %>
  <% end %>
</div>

app/views/relationships/_follow_user.html.erb
<table class="table">
  <thead>
   <tr>
    <th>image</th>
    <th>name</th>
    <th colspan="3"></th>
   </tr>
  </thead>
  <tbody>
   <% users.each do |user| %>
    <tr>
     <td><%= attachment_image_tag user, :profile_image, format: 'jpeg', fallback: "no-image-icon.jpg", size: "120x120", class: "rounded-circle m-4" %></td>
     <td><%= user.name %></td>
     <td>フォロー数: <%= user.followings.count%></td>
     <td>フォロワー数: <%= user.followers.count%></td>
     <td><%= link_to "詳細をみる", user_path(user), class: "user_#{user.id}" %></td>
    </tr>
   <% end %>
  </tbody>
</table>

app/views/relationships/create.js.erb
$(".follow").html("<%= j(render 'relationships/follow_button', user: @user ) %>");
$(".follow-count").html("<%= @user.followers.count %>");

app/views/relationships/destroy.js.erb
$(".follow").html("<%= j(render 'relationships/follow_button', user: @user ) %>");
$(".follow-count").html("<%= @user.followers.count %>");

app/views/relationships/followers.html.erb
<div class="container">
  <div class="row">
    <div class="col">
    <h2>フォロワー</h2>
      <% if @users.exists? %>
        <%= render 'relationships/follow_user', users: @users %>
      <% else %>
        <p>ユーザーはいません</p>
      <% end %>
   </div>
  </div>
</div>

app/views/relationships/followings.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <h2>フォロー中</h2>
      <% if @users.exists? %>
        <%= render 'relationships/follow_user', users: @users %>
      <% else %>
        <p>ユーザーはいません</p>
      <% end %>
    </div>
  </div>
</div>