config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  post '/homes/guest_sign_in', to: 'homes#new_guest'
  root 'homes#top'
  get 'homes/about'
  get '/search', to: 'searchs#search'

  resources :items do
    resources :item_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end

  resources :users, only: [:show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end
  resources :coordinetes, only: [:index, :create, :edit, :update, :destroy]
end

app/models/coordinete.rb
class Coordinete < ApplicationRecord
  has_many :coordinete_tables, dependent: :destroy
  belongs_to :user
  validates :name, presence: true, length: { in: 2..20 }
end

app/models/coordinete_table.rb
class CoordineteTable < ApplicationRecord
  belongs_to :item
  belongs_to :coordinete
  validates :item_id, presence: true
  validates :coordinete_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :items, dependent: :destroy
  has_many :item_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :coordinetes, dependent: :destroy
  has_many :recommendations
  # フォロー機能
  has_many :relationships
  has_many :followings, through: :relationships, source: :follow
  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'follow_id'
  has_many :followers, through: :reverse_of_relationships, source: :user

  validates :name, presence: true, uniqueness: true, length: { in: 2..20 }
  validates :introduction, length: { maximum: 50 }
  attachment :profile_image
  
  def me?(user_id)
    id == user_id
  end

  def follow(other_user)
    unless self == other_user
      relationships.find_or_create_by(follow_id: other_user.id)
    end
  end

  def unfollow(other_user)
    relationship = relationships.find_by(follow_id: other_user.id)
    relationship.destroy if relationship
  end

  def following?(other_user)
    followings.include?(other_user)
  end

  def self.search_for(content, method)
    if method == 'perfect'
      where(name: content)
    elsif method == 'forward'
      where('name LIKE ?', content + '%')
    elsif method == 'backward'
      where('name LIKE ?', '%' + content)
    else
      where('name LIKE ?', '%' + content + '%')
    end
  end
end

app/controllers/coordinetes_controller.rb
class CoordinetesController < ApplicationController
  before_action :ensure_coordinete, only: [:edit, :update, :destroy]

  def index
    @coordinetes = Coordinete.where(user_id: current_user.id)
    @coordinete = Coordinete.new
  end

  def create
    @coordinete = Coordinete.new(coordinete_params)
    @coordinete.user_id = current_user.id
    if @coordinete.save
      item_ids.each do |item_id|
        @coordinete.coordinete_tables.new(item_id: item_id)
        @coordinete.coordinete_tables
      end
      if @coordinete.save 
        #親クラスと子クラスが一緒にsave出来なかったので分けました。
        #リファクタリングすること
        flash[:notice] = "コーディネートを追加しました"
        redirect_to coordinetes_path
      else
        @coordinetes = Coordinete.all
        render :index
      end
    else
      @coordinetes = Coordinete.all
      render :index
    end
  end

  def edit
    if @coordinete.user != current_user
      redirect_to user_path(current_user)
    end
  end

  def update
    if @coordinete.update(coordinete_params)
      flash[:notice] = "コーディネートを編集しました"
      redirect_to coordinetes_path
    else
      render :edit
    end
  end

  def destroy
    @coordinete.destroy
    @coordinetes = Coordinete.all
    redirect_to coordinetes_path
  end

  private

  def coordinete_params
    params.require(:coordinete).permit(:name)
  end

  def item_ids
    params[:coordinete][:item_ids].values.map(&:to_i)
  end

  def ensure_coordinete
    @coordinete = Coordinete.find(params[:id])
  end
end

app/helpers/coordinetes_helper.rb
module CoordinetesHelper
end

app/views/coordinetes/_form.html.erb
 <div class="container text-right m-3">
    <div class="row">
      <div class="col">
        <button type="button" class="btn btn-info" data-toggle="modal" data-target="#exampleModal">
          コーディネートを追加
        </button>
      </div>
    </div>
  </div>
    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">コーディネート登録</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <% if current_user.items.empty? %>
              <p>先にアイテムを登録しましょう</p>
            <% else %>
              <%= form_with model: coordinete, url:coordinetes_path(coordinete), local:true do |f| %>
                <div class="modal-body">
                  <div class="form-group">
                   <%= f.label :アイテム① %>
                   <%= f.collection_select 'item_ids[0]', Item.where(user_id: current_user.id), :id, :name %>
                 </div>

                 <div class="form-group">
                   <%= f.label :アイテム② %>
                   <%= f.collection_select 'item_ids[1]', Item.where(user_id: current_user.id), :id, :name %>
                 </div>

                 <div class="form-group">
                   <%= f.label :アイテム③ %>
                   <%= f.collection_select 'item_ids[2]', Item.where(user_id: current_user.id), :id, :name %>
                 </div>

                 <div class="form-group">
                  <%= f.label :コーディネート名 %>
                  <%= f.text_area :name, placeholder: "ここへ記入", class: "form-control-file" %>
                </div>
                <div class="modal-footer">
                  <div class="form-group">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <%= f.submit "追加", class: 'btn btn-success'%>
                  </div>
                </div>
              <% end %>
          <% end %>
          </div>
        </div>
      </div>
    </div>

app/views/coordinetes/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <%= form_with model: @coordinete, local:true do |f| %>
        <div class="form-group">
          <%= f.label :アイテム① %><br >
          <%= f.collection_select 'item_ids[0]', Item.all, :id, :name %>
        </div>

        <div class="form-group">
          <%= f.label :アイテム② %><br >
          <%= f.collection_select 'item_ids[1]', Item.all, :id, :name %>
        </div>

        <div class="form-group">
          <%= f.label :アイテム③ %><br >
          <%= f.collection_select 'item_ids[2]', Item.all, :id, :name %>
        </div>

        <div class="form-group">
          <%= f.label :コーディネート名 %><br >
          <%= f.text_area :name, placeholder: "ここへ記入" %>
        </div>
        <div class="form-group">
          <%= f.submit "追加", class: 'btn btn-success'%>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/coordinetes/index.html.erb
<div class="container">
  <div class="row">
    <%= render 'layouts/errors', obj: @coordinete %>
    <%= render "coordinetes/form", coordinete: @coordinete %>
    <div class="col">
      <table class="table">
        <thead>
         <tr>
          <th>コーディネート名</th>
          <th>組み合わせ</th>
          <th colspan="3"></th>
         </tr>
        </thead>
        <tbody>
         <% @coordinetes.each do |coordinete| %>
          <tr>
            <td>
              <%= coordinete.name %>
            </td>
             <td>
              <% coordinete.coordinete_tables.each.with_index(1) do |coordinete_table, index| %>
                <%= "#{coordinete_table.item.name} #{'x' if index < coordinete.coordinete_tables.size}" %>
              <% end %>
            </td>
            <td><%= link_to "edit", edit_coordinete_path(coordinete), class: "btn btn-sm btn-success m-2" %></td>
            <td><%= link_to "destroy", coordinete_path(coordinete), method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-sm btn-danger m-2" %></td>
          </tr>
         <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>