config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  post '/homes/guest_sign_in', to: 'homes#new_guest'
  root 'homes#top'
  get 'homes/about'
  get '/search', to: 'searchs#search'

  resources :items do
    resources :item_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end

  resources :users, only: [:show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end
  resources :coordinetes, only: [:index, :create, :edit, :update, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/coordinete.rb
class Coordinete < ApplicationRecord
  has_many :coordinete_tables, dependent: :destroy
  belongs_to :user
  validates :name, presence: true, length: { in: 2..20 }
end

app/models/coordinete_table.rb
class CoordineteTable < ApplicationRecord
  belongs_to :item
  belongs_to :coordinete
  validates :item_id, presence: true
  validates :coordinete_id, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :item
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items
  has_many :recommendations
  validates :name, presence: true, uniqueness: true
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user
  belongs_to :genre
  has_many :item_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :coordinete_tables, dependent: :destroy
  has_many :recommendations

  validates :name, presence: true, length: { in: 2..30 }
  validates :shop_name, presence: true, length: { maximum: 30 }
  validates :detail, presence: true, length: { maximum: 200 }
  validates :private, inclusion: { in: [true, false] }
  attachment :image
  
  scope :published, -> { where(private: true) }

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  def self.search_for(content, method)
    if method == 'perfect'
      where(name: content)
    elsif method == 'forward'
      where('name LIKE ?', content + '%')
    elsif method == 'backward'
      where('name LIKE ?', '%' + content)
    else
      where('name LIKE ?', '%' + content + '%')
    end
  end
end

app/models/item_comment.rb
class ItemComment < ApplicationRecord
  belongs_to :user
  belongs_to :item
  validates :comment, presence: true, length: { in: 2..140 }
end

app/models/recommendation.rb
class Recommendation < ApplicationRecord
  belongs_to :user
  belongs_to :item
  belongs_to :genre
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :user
  belongs_to :follow, class_name: 'User'

  validates :user_id, presence: true
  validates :follow_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :items, dependent: :destroy
  has_many :item_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :coordinetes, dependent: :destroy
  has_many :recommendations
  # フォロー機能
  has_many :relationships
  has_many :followings, through: :relationships, source: :follow
  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'follow_id'
  has_many :followers, through: :reverse_of_relationships, source: :user

  validates :name, presence: true, uniqueness: true, length: { in: 2..20 }
  validates :introduction, length: { maximum: 50 }
  attachment :profile_image
  
  def me?(user_id)
    id == user_id
  end

  def follow(other_user)
    unless self == other_user
      relationships.find_or_create_by(follow_id: other_user.id)
    end
  end

  def unfollow(other_user)
    relationship = relationships.find_by(follow_id: other_user.id)
    relationship.destroy if relationship
  end

  def following?(other_user)
    followings.include?(other_user)
  end

  def self.search_for(content, method)
    if method == 'perfect'
      where(name: content)
    elsif method == 'forward'
      where('name LIKE ?', content + '%')
    elsif method == 'backward'
      where('name LIKE ?', '%' + content)
    else
      where('name LIKE ?', '%' + content + '%')
    end
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  before_action :recommendations, only: [:top, :about]
  before_action :ranks, only: [:top, :about]

  def top
  end

  def about
  end

  def new_guest
    user = User.find_or_create_by!(email: "guest@example.com") do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "ゲストユーザー"
      user.prefecture = "沖縄県"
      user.introduction = "持っている服がすぐに確認できて服選びが快適!!コーディネートが作れて服選びが楽"
    end
    sign_in user
    redirect_to items_path, notice: "ゲストユーザーとしてログインしました。"
  end

  private

  def recommendations
    @recommendations = Recommendation.all
  end

  def ranks
    @all_favorite_ranks = Item.find(Favorite.group(:item_id).
                              order('count(item_id) desc').limit(3).pluck(:item_id))

    @all_comment_ranks = Item.find(ItemComment.group(:item_id).
                              order('count(item_id) desc').limit(3).pluck(:item_id))

    @all_genre_ranks = Item.find(Item.group(:genre_id).
                              order('count(genre_id) desc').limit(3).pluck(:genre_id))
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :ensure_item, only: [:show, :edit, :update, :destroy]
  before_action :ranks, only: [:index]

  def new
    @item = Item.new
  end

  def index
    @items = Item.published.page(params[:page]).reverse_order
    @item_comment = ItemComment.new
    @recommendations = Recommendation.all
  end

  def create
    @item = Item.new(item_params)
    @item.user_id = current_user.id
    if @item.save
      redirect_to items_path, notice: '登録できました'
    else
      render :new
    end
  end

  def show
    @item_comment = ItemComment.new
  end

  def edit
    if @item.user != current_user
      redirect_to items_path
    end
  end

  def update
    if @item.update(item_params)
      redirect_to item_path(@item), notice: '変更しました'
    else
      render :edit
    end
  end

  def destroy
    @item.destroy
    redirect_to items_path
  end

  private

  def ranks
    @all_favorite_ranks = Item.find(Favorite.group(:item_id).
                              order('count(item_id) desc').limit(3).pluck(:item_id))

    @all_comment_ranks = Item.find(ItemComment.group(:item_id).
                              order('count(item_id) desc').limit(3).pluck(:item_id))

    @all_genre_ranks = Item.find(Item.group(:genre_id).
                              order('count(genre_id) desc').limit(3).pluck(:genre_id))
  end

  def item_params
    params.require(:item).permit(:genre_id, :name, :shop_name, :detail, :image, :private)
  end

  def ensure_item
    @item = Item.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_user, only: [:show, :edit, :update]

  def show
    if !@user.me?(current_user)
      @items = @user.items.published
    else
      @items = @user.items
    end
  end

  def edit
    if @user != current_user
      redirect_to user_path(current_user)
    end
  end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user.id), notice: '変更しました。'
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction, :prefecture)
  end

  def ensure_user
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/coordinetes_helper.rb
module CoordinetesHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/item_comments_helper.rb
module ItemCommentsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/searchs_helper.rb
module SearchsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/items/_btn_comment.html.erb
  <div class="container text-right my-3">
      <div class="row">
        <div class="col">
          <button type="button" class="btn btn-info" data-toggle="modal" data-target="#exampleModal">
            コメントを書く
          </button>
        </div>
      </div>
    </div>
    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel"><%= item.name %></h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <%= form_with model:[item, item_comment] do |f| %>
            <div class="modal-body">
              <div class="form-group">
                <%= render 'layouts/errors', obj: item_comment %>
                <%= f.label :コメント %>
                <%= f.text_area :comment, placeholder: "ここへ記入", class: "form-control-file" %>
              </div>
              <div class="modal-footer">
                <div class="form-group">
                  <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                  <%= f.submit "送信する", class: 'btn btn-success'%>
                </div>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>

app/views/items/_comment.html.erb
<% item.item_comments.order(created_at: :desc) .each do |item_comment| %>
 <table class="table">
   <tbody>
    <tr>
      <td>
        <%= link_to user_path(item_comment.item.user) do %>
          <%= attachment_image_tag item_comment.user, :profile_image, format: 'jpeg', fallback: "no-image-icon.jpg", size: "100x100",class: "m-2 rounded-circle" %>
        <% end %>
      </td>
      <td>
        <%= link_to user_path(item_comment.item.user) do%>
          <%= item_comment.user.name %>
        <% end %>
      </td>
      <td><%= item_comment.created_at.strftime('%Y/%m/%d') %></td>
      <td><%= item_comment.comment %></td>
      <% if item_comment.user == current_user %>
        <td>
          <%= link_to "コメントを削除",  item_item_comment_path(item_comment.item, item_comment), data: { confirm: '本当に消しますか？' }, class: "btn btn-secondary", method: :delete, remote: true  %>
        </td>
      <% end %>
    </tr>
   </tbody>
</table>
<% end %>

app/views/items/_favorites.html.erb
<% if user_signed_in? %>
  <% if item.favorited_by?(current_user) %>
    <p>
      <%= link_to item_favorites_path(item), {method: :delete, remote: true, id: "favorites_#{item.id}"} do %>
        ♥<%= item.favorites.count %>
      <% end %>
    </p>
  <% else %>
    <p>
      <%= link_to item_favorites_path(item), {method: :post, remote: true, id: "favorites_#{item.id}"} do %>
        ♡<%= item.favorites.count %>
      <% end %>
    </p>
  <% end %>
<% else %>
  <p>
    ♡<%= item.favorites.count %>
  </p>
<% end %>

app/views/items/_from.html.erb
<%= render 'layouts/errors', obj: @item %>
<%= form_with model: item, local:true do |f| %>
  <div class="form-group">
    <div class="row">
      <div class="col-6">
        <%= f.label :ジャンル %>
      </div>
      <div class="col">
        <%= f.collection_select :genre_id, Genre.all, :id, :name %>
      </div>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :アイテム %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :ブランド %>
    <%= f.text_area :shop_name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :説明 %>
    <%= f.text_area :detail, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :写真 %>
    <%= f.attachment_field :image, class: "form-control-file" %>
  </div>

  <div class="form-group">
    <div class="row m-3">
      <div class="col-6">
        <%= f.radio_button :private, false %><%= f.label :private, "非公開", class: "text-active" %>
      </div>
      <div class="col-6">
        <%= f.radio_button :private, true %><%= f.label :private, "公開", class: "text-invalid" %>
      </div>
    </div>
  </div>

  <div class="form-group">
    <%= f.submit class: 'btn btn-success' %>
  </div>
<% end %>

app/views/items/_index.html.erb
<div class="container mt-5">
  <div class="row">
    <div class="col">
      <table class='table table-hover table-inverse'>
        <thead>
          <tr>
            <th>写真</th>
            <th>アイテム名</th>
            <th>ショップ名</th>
            <th>コメント数</th>
            <th>いいねの数</th>
          </tr>
        </thead>
        <tbody>
          <% items.each do |item| %>
            <tr>
              <td><%= link_to item_path(item) do %>
                 <%= attachment_image_tag item, :image, format: 'jpeg', fallback: "no_image.jpg", size: "100x100", class: "m-2 rounded-circle" %>
                <% end %>
              </td>
              <td><%= link_to item.name, item_path(item) %></td>
              <td><%= item.shop_name %></td>
              <td><%= item.item_comments.count%></td>
              <td> <%= render 'items/favorites', item: item %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/items/_ranks.html.erb
<div class="row my-4">
    <div class="col-4">
      <div class="card border-secondary mb-3" style="max-width: 22rem;">
       <div class="card-header text-center">いいね数ランキング</div>
        <div class="card-body text-secondary">
          <% if all_favorite_ranks.count == 0 %>
            <p class="card-text">ランキングがありません</p>
          <% else %>
            <% all_favorite_ranks.each.with_index(1) do |item, i| %>
              <p class="card-text m-4">
                第<%= i %>位
                <%= item.favorites.count %>件
                <%=link_to item_path(item) do %>
                  <%= item.name%>
                <% end %>
              </p>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
    <div class="col-4">
      <div class="card border-secondary mb-3" style="max-width: 22rem;">
       <div class="card-header text-center">コメントランキング</div>
        <div class="card-body text-secondary">
          <% if all_comment_ranks.count == 0 %>
              <p class="card-text">ランキングがありません</p>
          <% else %>
            <% all_comment_ranks.each.with_index(1) do |item, i| %>
              <p class="m-4">
                第<%= i %>位
                <%= item.item_comments.count %>件
                <%=link_to item_path(item) do %>
                  <%= item.name %>
                <% end %>
              </p>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
    <div class="col-4 xs-12">
      <div class="card border-secondary mb-3" style="max-width: 22rem;">
       <div class="card-header text-center">ジャンルランキング</div>
        <div class="card-body text-secondary">
          <% if all_genre_ranks.count == 0 %>
              <p>ランキングがありません</p>
          <% else %>
            <% all_genre_ranks.each.with_index(1) do |item, i| %>
              <p class="m-4">
                第<%= i %>位
                <%= item.genre.name %>
              </p>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
   </div>

app/views/items/_recommendations.html.erb
<p>おすすめのアイテム(１分ごとにランダムで表示します)</p>
  <div class="row">
    <% recommendations.each do |recommendation| %>
      <% item = recommendation.item %>
      <div class="col-4">
        <div class="card my-2" style="width: 22rem;">
            <%= attachment_image_tag item, :image, fallback: "no_image.jpg", :size => '335x335', class: "m-2" %>
          <div class="card-body">
            <h5 class="card-title"><%= item.name %></h5>
            <small class="text-muted"><%= item.genre.name %></small>
            <p class="card-text"><%= item.shop_name %></p>
            <p><%= link_to "詳細をみる", item_path(item), class: "btn btn-primary" %></p>
            <div class="row">
              <div class="col-6"><i class="far fa-comment-dots"></i><%= "#{item.item_comments.count}"%></div>
              <%= render 'items/favorites', item: item %>
            </div>
            <p>
              <%= link_to user_path(item.user) do %>
                Name"<%= item.user.name %>"
              <% end %>
            </p>
          </div>
        </div>
      </div>
    <% end %>
  </div>

app/views/items/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
  		<h5>アイテムの編集</h5>
  		<%= render 'items/from', item: @item %>
  		<%= link_to '詳細ページへ', item_path(@item)%>
  		<%= link_to '戻る', items_path %>
  </div>
</div>

app/views/items/index.html.erb
<div class="container">
  <%= render 'layouts/weather_api'%>
  <%= render 'items/recommendations', recommendations: @recommendations %>
  <%= render 'items/ranks', all_favorite_ranks: @all_favorite_ranks, all_comment_ranks: @all_comment_ranks, all_genre_ranks: @all_genre_ranks %>
  <p>アイテム一覧</p>
  <div class="row">
   <% @items.each do |item| %>
    <div class="col-4 xs-12">
      <div class="card my-2" style="width: 22rem;">
         <%= attachment_image_tag item, :image, fallback: "no_image.jpg", :size => '335x335', class: "m-2" %>
        <div class="card-body">
          <h5 class="card-title"><%= item.name %></h5>
          <small class="text-muted"><%= item.genre.name %></small>
          <p class="card-text"><%= item.shop_name %></p>
          <p><%= link_to "詳細をみる", item_path(item.id), class: "btn btn-primary" %></p>
          <div class="row">
            <div class="col-6"><i class="far fa-comment-dots"></i><%= "#{item.item_comments.count}"%></div>
            <%= render 'items/favorites', item: item %>
          </div>
          <p>
            <%= link_to user_path(item.user) do %>
              Name"<%= item.user.name %>"
            <% end %>
          </p>
        </div>
      </div>
    </div>
   <% end %>
  </div>
  <div class="mx-auto"><%= paginate @items %></div>
</div>

app/views/items/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h4 class="mb-4">アイテムの追加</h4>
      <%= render 'items/from', item: @item %>
    </div>
  </div>
</div>

app/views/items/show.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <div class="card mb-3" style="max-width: 1200px;">
        <div class="row g-0">
          <div class="col">
            <%= attachment_image_tag @item, :image, fallback: "no_image.jpg", :size => '400x400', class: "m-3" %>
          </div>
              <div class="card-body col-md-6">
                <h5 class="card-title">アイテムの詳細</h5>
                <p class="card-text">ユーザー名 :　<%= link_to user_path(@item.user) do %><%= @item.user.name %><% end %></p>
                <p class="card-text">ジャンル名 :　<%= @item.genre.name %></p>
                <p class="card-text">アイテム名 :　<%= @item.name %></p>
                <p class="card-text">ブランド名 :　<%= @item.shop_name %></p>
                <p class="card-text">説明　　　 :　<%= @item.detail %></p>
                  <% if @item.private == false %>
                    <p class = "text-secondary">非公開</p>
                  <% else %>
                    <p class = "text-success">公開</p>
                  <% end %>
                </p>
                <div class="row">
                  <div class="col-6"><i class="far fa-comment-dots"></i>
                  <span class="comments-count" ><%= @item.item_comments.count%></span>
                </div>
                  <%= render 'items/favorites', item: @item %>
                </div>
                <% if @item.user == current_user %>
                <div class="row">
                  <div class="col-6">
                    <%= link_to 'アイテムを編集', edit_item_path(@item), class: "btn btn-sm btn-success m-2" %>
                  </div>
                  <div class="col">
                    <%= link_to "アイテムを削除", item_path(@item), method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-sm btn-danger m-2" %>
                  </div>
                </div>
                <% end %>

              <p class="card-text m-5"><small class="text-muted"><%= @item.created_at.strftime('%Y/%m/%d') %></small></p>
            </div>
          </div>
        </div>
      </div>
    </div>
    <%= render "items/btn_comment", item: @item, item_comment: @item_comment %>
     <div class="col m-5">
        <p>コメント欄</p>
      <div class="comments">
          <%= render "items/comment", item: @item, item_comment: @item_comment %>
      </div>
    </div>
  </div>
</div>

app/views/users/_index.html.erb
<div class="container mt-5">
 <div class="row">
  <div class="col">
   <table class='table table-hover table-inverse'>
     <thead>
      <tr>
       <th>写真</th>
       <th>名前</th>
       <th colspan="3"></th>
      </tr>
     </thead>
     <tbody>
      <% users.each do |user| %>
       <tr>
        <td>
          <%= link_to user_path(user) do %>
            <%= attachment_image_tag user, :profile_image, format: 'jpeg', fallback: "no-image-icon.jpg", size: "100x100", class: "rounded-circle" %>
          <% end %>
         </td>
        <td>
          <%= link_to user_path(user) do %>
            <%=user.name %>
          <% end %>
         </td>
        <td>フォロー数: <%= user.followings.count%></td>
        <td>フォロワー数: <%= user.followers.count%></td>
       </tr>
      <% end %>
     </tbody>
   </table>
  </div>
 </div>
</div>

app/views/users/edit.html.erb
<div class="container">
    <%= render 'layouts/errors', obj: @user %>
  <div class="row">
    <%= attachment_image_tag @user, :profile_image, format: 'jpeg', fallback: "no-image-icon.jpg", size: "120x120", class: "rounded-circle m-4" %>

    <div class="col">
      <h5 class="m-5">プロフィールの編集</h5>
      <%= form_with model:@user, local:true do |f| %>
        <div class="form-group">
         <%= f.label :"名前" %>
         <%= f.text_field :name, class: "form-control m-3" %>
        </div>

        <div class="form-group">
          <%= f.label :"紹介文" %>
          <%= f.text_area :introduction, class: "form-control m-3" %>
        </div>

        <div class="form-group">
          <%= f.label :"都道府県名" %>
          <%= f.text_field :prefecture, class: "form-control m-3" %>
        </div>

        <div class="form-group">
          <%= f.label :"写真" %>
          <%= f.attachment_field :profile_image, class: "m-3" %>
        </div>
         <div class="form-group">
          <%= f.submit class: 'btn btn-secondary' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <div class="row">
        <div class="col-3">
          <%= attachment_image_tag @user, :profile_image, format: 'jpeg', fallback: "no-image-icon.jpg", size: "120x120", class: "rounded-circle m-4" %>
        </div>
        <div class="col-8"><%= render 'layouts/weather_api'%></div>
        <div class="col-1">
          <div class="follow mt-5"><%= render 'relationships/follow_button', user: @user %></div>
        </div>
      </div>
       <div class="row m-4">
         <div class="col-5 textcenter">名前　:　<%= @user.name %></div>
         <div class="col-3 text-center">フォロー中　:　<%= link_to @user.followings.count, user_followings_path(@user) %></div>
         <div class="col-3 text-center">フォロワー　:　<%= link_to @user.followers.count, user_followers_path(@user), class: "follow-count" %></div>
       </div>
       <div class="row m-4">
         紹介文　:　<%= @user.introduction %>
       </div>
       <% if current_user == @user %>
        <div class="text-right"><%= link_to "コーディネート", coordinetes_path, class:"btn btn-info m-5" %></div>
       <% end%>

      <section>
        <h5>私のおすすめ服</h5>

        <% @items.each do |item| %>
          <%= link_to item_path(item) do%>
            <%= attachment_image_tag item, :image, format: 'jpeg', fallback: "no_image.jpg", size: "150x150", class: "m-1" %>
          <% end %>
        <% end %>
      </section>
    </div>
    </div>
  </div>
</div>