config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  post '/homes/guest_sign_in', to: 'homes#new_guest'
  root 'homes#top'
  get 'homes/about'
  get '/search', to: 'searchs#search'

  resources :items do
    resources :item_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end

  resources :users, only: [:show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end
  resources :coordinetes, only: [:index, :create, :edit, :update, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/coordinete.rb
class Coordinete < ApplicationRecord
  has_many :coordinete_tables, dependent: :destroy
  belongs_to :user
  validates :name, presence: true, length: { in: 2..20 }
end

app/models/coordinete_table.rb
class CoordineteTable < ApplicationRecord
  belongs_to :item
  belongs_to :coordinete
  validates :item_id, presence: true
  validates :coordinete_id, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :item
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items
  has_many :recommendations
  validates :name, presence: true, uniqueness: true
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user
  belongs_to :genre
  has_many :item_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :coordinete_tables, dependent: :destroy
  has_many :recommendations

  validates :name, presence: true, length: { in: 2..30 }
  validates :shop_name, presence: true, length: { maximum: 30 }
  validates :detail, presence: true, length: { maximum: 200 }
  validates :private, inclusion: { in: [true, false] }
  attachment :image
  
  scope :published, -> { where(private: true) }

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  def self.search_for(content, method)
    if method == 'perfect'
      where(name: content)
    elsif method == 'forward'
      where('name LIKE ?', content + '%')
    elsif method == 'backward'
      where('name LIKE ?', '%' + content)
    else
      where('name LIKE ?', '%' + content + '%')
    end
  end
end

app/models/item_comment.rb
class ItemComment < ApplicationRecord
  belongs_to :user
  belongs_to :item
  validates :comment, presence: true, length: { in: 2..140 }
end

app/models/recommendation.rb
class Recommendation < ApplicationRecord
  belongs_to :user
  belongs_to :item
  belongs_to :genre
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :user
  belongs_to :follow, class_name: 'User'

  validates :user_id, presence: true
  validates :follow_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :items, dependent: :destroy
  has_many :item_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :coordinetes, dependent: :destroy
  has_many :recommendations
  # フォロー機能
  has_many :relationships
  has_many :followings, through: :relationships, source: :follow
  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'follow_id'
  has_many :followers, through: :reverse_of_relationships, source: :user

  validates :name, presence: true, uniqueness: true, length: { in: 2..20 }
  validates :introduction, length: { maximum: 50 }
  attachment :profile_image
  
  def me?(user_id)
    id == user_id
  end

  def follow(other_user)
    unless self == other_user
      relationships.find_or_create_by(follow_id: other_user.id)
    end
  end

  def unfollow(other_user)
    relationship = relationships.find_by(follow_id: other_user.id)
    relationship.destroy if relationship
  end

  def following?(other_user)
    followings.include?(other_user)
  end

  def self.search_for(content, method)
    if method == 'perfect'
      where(name: content)
    elsif method == 'forward'
      where('name LIKE ?', content + '%')
    elsif method == 'backward'
      where('name LIKE ?', '%' + content)
    else
      where('name LIKE ?', '%' + content + '%')
    end
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  before_action :recommendations, only: [:top, :about]
  before_action :ranks, only: [:top, :about]

  def top
  end

  def about
  end

  def new_guest
    user = User.find_or_create_by!(email: "guest@example.com") do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "ゲストユーザー"
      user.prefecture = "沖縄県"
      user.introduction = "持っている服がすぐに確認できて服選びが快適!!コーディネートが作れて服選びが楽"
    end
    sign_in user
    redirect_to items_path, notice: "ゲストユーザーとしてログインしました。"
  end

  private

  def recommendations
    @recommendations = Recommendation.all
  end

  def ranks
    @all_favorite_ranks = Item.find(Favorite.group(:item_id).
                              order('count(item_id) desc').limit(3).pluck(:item_id))

    @all_comment_ranks = Item.find(ItemComment.group(:item_id).
                              order('count(item_id) desc').limit(3).pluck(:item_id))

    @all_genre_ranks = Item.find(Item.group(:genre_id).
                              order('count(genre_id) desc').limit(3).pluck(:genre_id))
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :ensure_item, only: [:show, :edit, :update, :destroy]
  before_action :ranks, only: [:index]

  def new
    @item = Item.new
  end

  def index
    @items = Item.published.page(params[:page]).reverse_order
    @item_comment = ItemComment.new
    @recommendations = Recommendation.all
  end

  def create
    @item = Item.new(item_params)
    @item.user_id = current_user.id
    if @item.save
      redirect_to items_path, notice: '登録できました'
    else
      render :new
    end
  end

  def show
    @item_comment = ItemComment.new
  end

  def edit
    if @item.user != current_user
      redirect_to items_path
    end
  end

  def update
    if @item.update(item_params)
      redirect_to item_path(@item), notice: '変更しました'
    else
      render :edit
    end
  end

  def destroy
    @item.destroy
    redirect_to items_path
  end

  private

  def ranks
    @all_favorite_ranks = Item.find(Favorite.group(:item_id).
                              order('count(item_id) desc').limit(3).pluck(:item_id))

    @all_comment_ranks = Item.find(ItemComment.group(:item_id).
                              order('count(item_id) desc').limit(3).pluck(:item_id))

    @all_genre_ranks = Item.find(Item.group(:genre_id).
                              order('count(genre_id) desc').limit(3).pluck(:genre_id))
  end

  def item_params
    params.require(:item).permit(:genre_id, :name, :shop_name, :detail, :image, :private)
  end

  def ensure_item
    @item = Item.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/coordinetes_helper.rb
module CoordinetesHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/searchs_helper.rb
module SearchsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_errors.html.erb
<% if obj.errors.any? %>
  <div id="error_explanation">
    <ul>
      <% obj.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_weather_api.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <% if current_user.prefecture.blank?%>
        <p>都道府県（県まで）登録すると天気予報表示できます</p>
      <% else%>
        <p><%= current_user.prefecture %>の天気です</p>
        <p class="row" id="weather"></p>
      <% end %>
    </div>
  </div>
</div>
<script>
  $(function () {
  var API_KEY = '<%= ENV['OPEN_WEATHER_MAP_API'] %>';
  var city = "<%= current_user.prefecture %>";
  var url = 'https://api.openweathermap.org/data/2.5/forecast?q=' + city + ',jp&units=metric&APPID=' + API_KEY;
  $.ajax({
      url: url,
      dataType: 'json',
      type: 'GET',
    })
    .done(function (data) {
      var insertHTML = '';
      var cityName = data.city.name;
      $('#city-name').html(cityName);
      for (var i = 0; i <= 32; i = i + 8) {
        insertHTML += buildHTML(data, i);
      }
      $('#weather').html(insertHTML);
    })
    .fail(function (data){
      alert('都道府県が見つかりませんでした。県まで追加してください');
    });
  });
   // 日本語化
  function buildHTML(data, i) {
    var Week = new Array('(日)', '(月)', '(火)', '(水)', '(木)', '(金)', '(土)');
    var date = new Date(data.list[i].dt_txt);
    date.setHours(date.getHours() + 9);
    var month = date.getMonth() + 1;
    var day = month + '/' + date.getDate() + Week[date.getDay()];
    var icon = data.list[i].weather[0].icon;
    var html =
      '<div class="weather-report">' +
        '<img src="https://openweathermap.org/img/w/' + icon + '.png">' +
        '<span class="weather-date">' + day + "</span>" +
        '<div class="weather-temp-max">' + '最高：' + Math.round(data.list[i].main.temp_max) + "℃</div>" +
        '<span class="weather-temp-min">' + '最低：' + Math.floor(data.list[i].main.temp_min) + "℃</span>" +
      '</div>';
    return html
  }
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyCloset</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <div class="header">
      <nav class="header navbar navbar-expand-lg navbar-dark ">
        <div class="container">
          <a class="navbar-brand" href="/"><span>My Closet</span></a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
             <% if user_signed_in? %>
               <li><%= link_to 'MyCloset      ', user_path(current_user.id), class: "fas fa-home nav-link text-white p-3" %></li>
               <li><%= link_to '投稿一覧      ', items_path, class: "fas fa-store-alt nav-link text-white p-3" %></li>
               <li><%= link_to '投稿フォーム  ', new_item_path, class: "fas fa-plus nav-link text-white p-3" %></li>
               <li><%= link_to 'log_out       ', destroy_user_session_path, method: :delete, class: "fas fa-sign-out-alt nav-link text-white p-3" %></li>
             <% else %>
               <li><%= link_to 'about         ', homes_about_path, class: "fas fa-paper-plane nav-link text-white p-3" %></li>
               <li><%= link_to 'sign_up       ', new_user_registration_path, class: "fas fa-user-plus nav-link text-white p-3" %></li>
               <li><%= link_to 'sign_in       ', new_user_session_path, class: "fas fa-sign-in-alt nav-link text-white p-3" %></li>
               <li><%= link_to 'ゲストログイン', homes_guest_sign_in_path, method: :post, class: "fas fa-sign-in-alt nav-link text-white p-3" %></li>
             <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </div>
      <p id="notice"><%= notice %></p>
      <div class="main pb-3">
        <%= render 'searchs/form' %>
        <%= yield %>
      </div>
    <div class="footer py-3">
      <p class="text-center text-white">mycloset.work</p>
    </div>
  </body>
</html>